name: Playwright E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Run E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          BASE_URL: ${{ secrets.BASE_URL || 'https://frontend-two-swart-31.vercel.app' }}
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('test-results.json', 'utf8'));
            
            const passed = results.suites.reduce((sum, suite) => 
              sum + suite.specs.filter(spec => spec.ok).length, 0);
            const failed = results.suites.reduce((sum, suite) => 
              sum + suite.specs.filter(spec => !spec.ok).length, 0);
            const total = passed + failed;
            
            const body = `## 🎭 Playwright Test Results
            
            - ✅ **Passed:** ${passed}/${total}
            - ❌ **Failed:** ${failed}/${total}
            - ⏱️ **Duration:** ${(results.duration / 1000).toFixed(2)}s
            
            ${failed > 0 ? '⚠️ Some tests failed. Check the [test report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.' : '✅ All tests passed!'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
